### ISSUE TITLE
add wikipedia service

### ISSUE THREAD

**Issue by LordSomen** [Eulercoder/fabulous#13]
I will try to add wikipedia service

**Comment by LordSomen** [comment]
Okk, I will use MediaWiki api to fetch a any search query.
like if the user type ~wiki searchitem it will give the url of the search item in wiki.

**Comment by vicky002** [comment]
Is it free? Any limit on the total number of API calls we can make?

**Comment by LordSomen** [comment]
yeah it is free , check out this : https://www.mediawiki.org/wiki/Web_APIs_hub . They have not say anything about limit , I don't think there is any limit.

**Comment by MatejMecka** [comment]
This should be closed. It's merged
