### ISSUE TITLE
Add News service.

### ISSUE THREAD

**Issue by roychowdhuryrohit-dev** [Eulercoder/fabulous#14]
I was wondering if news feature can be implemented by using News API based on categories, countries, languages.

**Comment by vicky002** [comment]
It will be good feature! 
@roychowdhuryrohit-dev you can start working on it.

**Comment by roychowdhuryrohit-dev** [comment]
I have added the news feature. A lot of work is still left regarding improvements.

**Comment by vicky002** [comment]
Hey @roychowdhuryrohit-dev, any update on this?

**Comment by vicky002** [comment]
Oh this is already done, should I close this issue? @roychowdhuryrohit-dev

**Comment by roychowdhuryrohit-dev** [comment]
Yes sure !
