### ISSUE TITLE
Add Google Search Service

### ISSUE THREAD

**Issue by anshulnsit** [Eulercoder/fabulous#15]
I will add google search service which can be accessed by typing ~google query

**Comment by vicky002** [comment]
@anshulnsit add description , label and milestone as seen in other issues. 

Help will help in understanding. :)

**Comment by anshulnsit** [comment]
@vicky002 I am not able to find the option to add labels. Can you please help me?

**Comment by vicky002** [comment]
done.

**Comment by anshulnsit** [comment]
@vicky002  Thank You

**Comment by vicky002** [comment]
Hey @anshulnsit , any update on this?

**Comment by anshulnsit** [comment]
@vicky002 Yes, I have successfully activated my api key and used it with python. Now I just want to return the url from JSON file. Will be completed soon

**Comment by anshulnsit** [comment]
@vicky002 I am getting some error due to dependency of google API on older versions of oauth2client. But I am not using that so I am also getting my results. Just want to ask that if there is any error in the output will the bot print that error in the slack or only my results?
