### ISSUE TITLE
~help in slack function breaks the last service in two line

### ISSUE THREAD

**Issue by vicky002** [Eulercoder/fabulous#48]
```
~yt `query` will return the top search result 
Log all messages to the database
news <location> <category> <language>will fetch news from news API
~calc <equation> will return the google calculator result for <equation>
~dict <search_term> will return the meaning and usage of <search_term>
~directions "<start>" "<end>" (in quotes) return a result from the google maps result for directions from <start> to <end>
~gif <search term> return a random result from the  google gif search result for <search term>
~google <search term> will return three results from the google search for <search term>
~help [<command>] prints help on all commands if no command given, or a specific command
~img <search term> return a random result from google search image related to the <search term>
~scores <sport> return the live scores for <sport>
~sof <your question> > will return the the result 
~stock <search_term> will return the real time result of that stock.
```
This
```
~translate <text> will return the goslate tra
nsalte result for <text> in English
```

**Comment by vitkhab** [comment]
It's a logic implemented here https://github.com/Eulercoder/fabulous/blob/master/fabulous/fabulous.py#L208
Fabulous will send long messages by blocks of 1000 letters.

@vicky002 what should be done to fix this issue? The problem won't be solved by raising limit only.
I propose two solutions:
- Leave as it is.
- Split messages on line breaks or spaces.

**Comment by vicky002** [comment]
Hey @vitkhab , Thanks for pointing this out. I don't know how I missed this piece of code. 

As we will be having many more services in the future and help function will get much bigger. There should be a way to show all the services we offer. 

I need to figure what would be the good way to handle this one. Maybe I can send an attachment but attachment won't be good for every single call. 

Marking it as unsolved, need to test and figure.

Thank you so much for finding the cause! I'll get back to this in a few days. 👍

**Comment by vicky002** [comment]
@Buffer0x7cd We will have to fix this issue before the beta release. Maybe after completing the documentation, testing and all things we have decided to do in the current tasks.

**Comment by vicky002** [comment]
@Buffer0x7cd if this is done, please close it.

**Comment by Buffer0x7cd** [comment]
Done in PR68
