### ISSUE TITLE
Import Error while running make repl

### ISSUE THREAD

**Issue by Buffer0x7cd** [Eulercoder/fabulous#53]
I am trying to install the fabulous bot on my system.
First I have created a virtual environment by using `virtualenv -p python3 venv`
After running the `make repl` i am getting import error. below is the screenshot of
the error
![screenshot from 2017-12-22 17-14-10](https://user-images.githubusercontent.com/16363909/34297222-d8d395ba-e73c-11e7-8ddc-c87612b8b83f.png)

**Comment by rusrushal13** [comment]
Can you do `pip install requests` manually on your virtualenv.

**Comment by Buffer0x7cd** [comment]
It's already installed. here is the response i am getting for `pip install requests`
`Requirement already satisfied: requests in /home/ubuntu/venv/lib/python3.5/site-packages`

**Comment by rusrushal13** [comment]
you could check `pip list` in your virtualenv for requests module, as the bot is using python2.7 and you are using python3.5.

**Comment by Buffer0x7cd** [comment]
I tried creating a python2 environment by using `virtualenv -p python2' but still getting the same problem.
here is the screenshot
![screenshot from 2017-12-22 17-58-02](https://user-images.githubusercontent.com/16363909/34298084-e3bb91da-e741-11e7-8120-155617d9d427.png)

**Comment by rusrushal13** [comment]
@vicky002 any idea?

**Comment by vicky002** [comment]
@rusrushal13 @Buffer0x7cd 

I'll try this one, give me some time.

**Comment by Buffer0x7cd** [comment]
Fixed. I was using an old version which had sudo in the Makefile
