### ISSUE TITLE
Q: Uses of both urllib and requests in service implementation. 

### ISSUE THREAD

**Issue by Buffer0x7cd** [Eulercoder/fabulous#56]
While looking through the implementation of different services, I noticed that some services used urllib for interacting with the external API while others used requests for the same. I was wondering if these uses are due to some different uses cases or just a matter of personal choice. If these changes are due to some edge cases then please let me know, because I was hoping to work on the services that use urllib and replace them with requests for consistency purpose.

**Comment by vicky002** [comment]
I don't think there are any edge cases, people contributed and used whatever they found working. 

Consider changing them all to requests.

**Comment by Buffer0x7cd** [comment]
Fixed
