### ISSUE TITLE
Add Weather support service

### ISSUE THREAD

**Issue by SouravRaha-dev** [Eulercoder/fabulous#8]
Add Weather Service which shows the current weather of the user entered place.

Example: ~weather search_city , it should display the current weather of the searched place

**Comment by roychowdhuryrohit-dev** [comment]
You can use Open Weather API.

**Comment by vicky002** [comment]
Hey @SouravRaha-dev , any update on this?

**Comment by adityagaikwad** [comment]
Hi, can I work on this issue? I have the bot running locally already. Please let me know asap!

**Comment by vicky002** [comment]
@adityagaikwad yes definitely.

**Comment by vicky002** [comment]
This task is assigned to @adityagaikwad now.

**Comment by adityagaikwad** [comment]
So I read up on openweathermap API. It allows 60 calls per minute for free. Will that be enough for now or should I look for another API?

**Comment by vicky002** [comment]
@adityagaikwad yes 👍

**Comment by adityagaikwad** [comment]
Can someone merge the pull request? I've made the changes long back..

**Comment by vicky002** [comment]
✔️
